import './index.sass'
import "@babel/polyfill"

// import AdvertList from './advert_list'
// import Banner from './banner'
// import Tab from './tabs/index'
// import EntryTab from './tabs/entryTab'
// import NormalList from './normalList'
// import RowList from './rowList'
// import OperationList from './operationList'
// import NewList from './newList'
// import CutList from './cutList'
// import GridList from './gridList'
// import GridList2 from './gridList2'
// import Title from './title'
// import Quote from './quote'
// import Paragraph from './paragraph'
// import ComImg from './com_img'
// import ComButton from './com_button'
// import ComFAQ from './com_faq'
// import ComFooter from './com_footer'
// import ComStep from './com_step'
// // 轮播图
// import Carousel from './carousel'

// export {
//     AdvertList, Banner, Tab, EntryTab, NormalList, RowList, OperationList, NewList, CutList, GridList, GridList2, Title, Quote, Paragraph, ComImg, ComButton, ComFAQ, ComFooter, ComStep, Carousel
// }

export { default as Advert } from './advert_list'
export { default as Banner } from './banner'
export { default as Tab } from './tabs/index'
export { default as EntryTab } from './tabs/entryTab'
export { default as NormalList } from './normalList'
export { default as RowList } from './rowList'
export { default as OperationList } from './operationList'
export { default as NewList } from './newList'
export { default as CutList } from './cutList'
export { default as GridList } from './gridList'
export { default as GridList2 } from './gridList2'
export { default as Title } from './title'
export { default as Quote } from './quote'
export { default as Paragraph } from './paragraph'
export { default as ComImg } from './com_img'
export { default as ComButton } from './com_button'
export { default as ComFAQ } from './com_faq'
export { default as ComFooter } from './com_footer'
export { default as ComStep } from './com_step'
// 轮播图
export { default as Carousel } from './carousel'